name: Publish Presentation
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      

      - name: Build Marp Slide
        uses: marp-team/marp-cli-action@v1.1.2
        with:
          args: slides.md -o index.html --html
        env:
          MARP_USER: root:root
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Der Ordner, in dem die index.html liegt
